# Generated by Django 3.1.4 on 2021-01-06 08:16

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0004_auto_20210104_1913'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 6, 8, 16, 19, 392041, tzinfo=utc)),
        ),
    ]
